version: "3.6"
services:
  app:
    build: .
    ports:
      - 3001:3001
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:14.6
    environment:
      POSTGRES_USER: gateskennedy
      POSTGRES_PASSWORD: svRn47LUQRk8tiyAorL8FcxLZkJ8sybj
      POSTGRES_DB: aoe_auth_db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: